# Generated by Django 2.1.5 on 2019-01-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchtracking',
            old_name='sent_to_accountant',
            new_name='accountant_notified',
        ),
        migrations.RemoveField(
            model_name='batches',
            name='pieces_generated',
        ),
        migrations.AddField(
            model_name='batches',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batches',
            name='number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchtracking',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchtracking',
            name='pieces_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pieces',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batches',
            name='period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pieces',
            name='folder_assigned',
            field=models.CharField(blank=True, choices=[('Achats', 'Achats'), ('Banque', 'Banque'), ('Ventes', 'Ventes'), ('Caisse', 'Caisse'), ('OD', 'OD'), ('Rejects', 'Rejects'), ('Incomplete', 'Incomplete'), ('Doublons', 'Doublons'), ('Ged', 'Ged'), ('Forwarded', 'Forwarded')], max_length=255, null=True),
        ),
    ]
