# Generated by Django 2.1.5 on 2019-02-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folderchoises',
            options={'verbose_name': 'folder choice', 'verbose_name_plural': 'folder choices'},
        ),
    ]
