# Generated by Django 2.1.5 on 2019-01-27 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190127_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtracking',
            name='preparer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparers_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchtracking',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewers_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
