# Generated by Django 2.1.5 on 2019-01-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190127_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pieces',
            old_name='period',
            new_name='folder_month',
        ),
        migrations.RemoveField(
            model_name='batches',
            name='period',
        ),
        migrations.AddField(
            model_name='batches',
            name='month_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MY of Batch'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='chr_flag',
            field=models.BooleanField(verbose_name='CHR'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='e_comerce_flag',
            field=models.BooleanField(verbose_name='E commerce'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='vat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT date'),
        ),
    ]
