# Generated by Django 2.1.5 on 2019-01-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190127_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batches',
            name='name',
        ),
        migrations.AlterField(
            model_name='batches',
            name='month_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MonthYear'),
        ),
    ]
