# Generated by Django 2.1.5 on 2019-02-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190130_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pieces',
            options={'ordering': ['folder_original', 'file_name', 'batch'], 'verbose_name': 'piece', 'verbose_name_plural': 'pieces'},
        ),
    ]
