# Generated by Django 2.1.5 on 2019-01-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Reviewer'), (2, 'Preparer'), (3, 'Accountant')], default=1),
            preserve_default=False,
        ),
    ]
